### PR TITLE
Use commons-codec and commons-logging

### PR DESCRIPTION
**Pull request by merks**
https://github.com/eclipse-simrel/simrel.build/issues/438

### CODE REVIEW

**Comment by nitind** [comment]
Thanks, Ed!

**Comment by nitind** [comment]
@merks the version of httpclient we're pulling in from somewhere conflicts and won't build with this change https://ci.eclipse.org/webtools/view/webtools_CI/job/webtools-webservices_master/2704/:

`Bundle was not resolved because of a uses constraint violation.
  org.apache.felix.resolver.reason.ReasonException: Uses constraint violation. Unable to resolve resource org.eclipse.wst.wsi [osgi.identity; type="osgi.bundle"; version:Version="1.1.501.qualifier"; osgi.identity="org.eclipse.wst.wsi"; singleton:="true"] because it is exposed to package 'org.apache.commons.logging' from resources org.apache.commons.commons-logging [osgi.identity; type="osgi.bundle"; version:Version="1.3.3"; osgi.identity="org.apache.commons.commons-logging"] and org.apache.commons.logging [osgi.identity; type="osgi.bundle"; version:Version="1.2.0.v20180409-1502"; osgi.identity="org.apache.commons.logging"] via two dependency chains.

Chain 1:
  org.eclipse.wst.wsi [osgi.identity; type="osgi.bundle"; version:Version="1.1.501.qualifier"; osgi.identity="org.eclipse.wst.wsi"; singleton:="true"]
    require: (osgi.wiring.bundle=org.apache.commons.commons-logging)
     |
    provide: osgi.wiring.bundle: org.apache.commons.commons-logging
  org.apache.commons.commons-logging [osgi.identity; type="osgi.bundle"; version:Version="1.3.3"; osgi.identity="org.apache.commons.commons-logging"]

Chain 2:
  org.eclipse.wst.wsi [osgi.identity; type="osgi.bundle"; version:Version="1.1.501.qualifier"; osgi.identity="org.eclipse.wst.wsi"; singleton:="true"]
    import: (osgi.wiring.package=org.apache.http.impl.conn)
     |
    export: osgi.wiring.package=org.apache.http.impl.conn; uses:=org.apache.commons.logging
  org.apache.httpcomponents.httpclient [osgi.identity; type="osgi.bundle"; version:Version="4.5.14"; osgi.identity="org.apache.httpcomponents.httpclient"]
    import: (&(osgi.wiring.package=org.apache.commons.logging)(&(version>=1.1.0)(!(version>=1.3.0))))
     |
    export: osgi.wiring.package: org.apache.commons.logging
  org.apache.commons.logging [osgi.identity; type="osgi.bundle"; version:Version="1.2.0.v20180409-1502"; osgi.identity="org.apache.commons.logging"]`

**Comment by nitind** [comment]
I'm working on porting that class to use the v5 client, so that we're not the ones requiring v4 to stick around. We'll see how that goes.

**Comment by merks** [comment]
That sounds good.   

This bundle has a very restrictive version range dependency on the org.apache.commons.logging  package:

> [ERROR]   Missing requirement: org.apache.httpcomponents.httpasyncclient 4.1.5 requires 'java.package; org.apache.commons.logging [1.1.0,1.3.0)' but it could not be found

That bundle provides these packages:
```
    <provided namespace='java.package' name='org.apache.http.nio.client' version='4.1.5'/>
    <provided namespace='java.package' name='org.apache.http.nio.client.methods' version='4.1.5'/>
    <provided namespace='java.package' name='org.apache.http.nio.client.util' version='4.1.5'/>
    <provided namespace='java.package' name='org.apache.http.nio.conn' version='4.1.5'/>
    <provided namespace='java.package' name='org.apache.http.nio.conn.scheme' version='4.1.5'/>
    <provided namespace='java.package' name='org.apache.http.nio.conn.ssl' version='4.1.5'/>
    <provided namespace='java.package' name='org.apache.http.impl.nio.client' version='4.1.5'/>
    <provided namespace='java.package' name='org.apache.http.impl.nio.conn' version='4.1.5'/>
```

**Comment by nitind** [comment]
The wsi bundle was using the v4 http client bundle to validate headers, and I believe it'll now work against the v5 http core bundle. No orbit changes needed.

**Pull request merged**
